package promhs;

public class frmSIM extends javax.swing.JFrame {
    frmhs fm;
    frmdos fd;
    frmMK fk;
    
    public frmSIM() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        dskutama = new javax.swing.JDesktopPane();
        jMenuBar1 = new javax.swing.JMenuBar();
        MNFile = new javax.swing.JMenu();
        MNFileExit = new javax.swing.JMenuItem();
        MNmhs = new javax.swing.JMenu();
        MNDosen = new javax.swing.JMenu();
        MNMK = new javax.swing.JMenu();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        javax.swing.GroupLayout dskutamaLayout = new javax.swing.GroupLayout(dskutama);
        dskutama.setLayout(dskutamaLayout);
        dskutamaLayout.setHorizontalGroup(
            dskutamaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 1111, Short.MAX_VALUE)
        );
        dskutamaLayout.setVerticalGroup(
            dskutamaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 651, Short.MAX_VALUE)
        );

        getContentPane().add(dskutama, java.awt.BorderLayout.CENTER);

        MNFile.setText("File");

        MNFileExit.setText("Exit");
        MNFileExit.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                MNFileExitActionPerformed(evt);
            }
        });
        MNFile.add(MNFileExit);

        jMenuBar1.add(MNFile);

        MNmhs.setText("DataMahasiswa");
        MNmhs.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                MNmhsMouseClicked(evt);
            }
        });
        MNmhs.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                MNmhsActionPerformed(evt);
            }
        });
        jMenuBar1.add(MNmhs);

        MNDosen.setText("DataDosen");
        MNDosen.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                MNDosenMouseClicked(evt);
            }
        });
        MNDosen.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                MNDosenActionPerformed(evt);
            }
        });
        jMenuBar1.add(MNDosen);

        MNMK.setText("DataMatakuliah");
        MNMK.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                MNMKMouseClicked(evt);
            }
        });
        jMenuBar1.add(MNMK);

        setJMenuBar(jMenuBar1);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void MNFileExitActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_MNFileExitActionPerformed
        System.exit(0);
    }//GEN-LAST:event_MNFileExitActionPerformed

    private void MNmhsActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_MNmhsActionPerformed
        
    }//GEN-LAST:event_MNmhsActionPerformed

    private void MNmhsMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_MNmhsMouseClicked
        if(fm==null || fm.isClosed() ){
            fm = new frmhs();
            dskutama.add(fm);
            fm.setLocation(this.getWidth()/2 - fm.getWidth()/2, this.getHeight()/2-fm.getHeight()/2);
            fm.setVisible(true);
        }else{
            fm.setVisible(true);
        }
    }//GEN-LAST:event_MNmhsMouseClicked

    private void MNDosenActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_MNDosenActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_MNDosenActionPerformed

    private void MNDosenMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_MNDosenMouseClicked
       if(fd==null || fd.isClosed() ){
            fd = new frmdos();
            dskutama.add(fd);
            fd.setLocation(this.getWidth()/2 - fd.getWidth()/2, this.getHeight()/2-fd.getHeight()/2);
            fd.setVisible(true);
        }else{
            fd.setVisible(true);
        }
    }//GEN-LAST:event_MNDosenMouseClicked

    private void MNMKMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_MNMKMouseClicked
        if(fk==null || fk.isClosed() ){
            fk = new frmMK();
            dskutama.add(fk);
            fk.setLocation(this.getWidth()/2 - fk.getWidth()/2, this.getHeight()/2-fk.getHeight()/2);
            fk.setVisible(true);
        }else{
            fk.setVisible(true);
        }
    }//GEN-LAST:event_MNMKMouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(frmSIM.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(frmSIM.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(frmSIM.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(frmSIM.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new frmSIM().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JMenu MNDosen;
    private javax.swing.JMenu MNFile;
    private javax.swing.JMenuItem MNFileExit;
    private javax.swing.JMenu MNMK;
    private javax.swing.JMenu MNmhs;
    private javax.swing.JDesktopPane dskutama;
    private javax.swing.JMenuBar jMenuBar1;
    // End of variables declaration//GEN-END:variables
}
